GuideMeServerMVC/Models/MenuViewModel.cs
namespace GuideMeServerMVC.Models
{
    public class MenuViewModel
    {
        public UsuarioEstabelecimentoModel? UsuarioEstabelecimento { get; set; }
        public EstabelecimentoViewModel? Estabelecimento { get; set; }
    }
}

GuideMeServerMVC/Controllers/EstabelecimentoController.cs
using GuideMeServerMVC.Data;
using GuideMeServerMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using GuideMeServerMVC.Utils;
using System.Reflection;

namespace GuideMeServerMVC.Controllers
{
    public class EstabelecimentoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly GuidemeDbContext _context;

        public EstabelecimentoController(IConfiguration configuration, GuidemeDbContext context)
        {
            _configuration = configuration;
            _context = context;
        }
       
        public async Task<IActionResult> CadastrarEstabelecimento()
        {
            Debug.WriteLine("Chamou a tela de Cadastro de Estabelecimento!");
            return View("CadastroEstabelecimento", new EstabelecimentoViewModel());
        }
        public async Task<IActionResult> Create([FromForm] EstabelecimentoViewModel estabelecimento) //Create e Update
        {
            try
            {
                _context.Database.BeginTransaction();
                Debug.WriteLine("estabelecimento -> " + estabelecimento.Id);
                if (estabelecimento.Id == 0) //Create
                {
                    Debug.WriteLine("CreateEstabelecimento");
                    //Cadastrar o estabelecimento
                    _context.Estabelecimento.Add(estabelecimento);
                    _context.SaveChanges();
                    Debug.WriteLine("Estabelecimento criado");

                    //Pegar o id do estabelecimento inserido e relaciona-lo ao usuario
                    Debug.WriteLine("Estabelecimento Id => " + estabelecimento.Id);
                    Debug.WriteLine("HttpContext.Session.GetInt32(UserId) => " + HttpContext.Session.GetInt32("UserId"));
                    var user = _context.UsuariosEstabelecimento.FirstOrDefault(o => o.Id == HttpContext.Session.GetInt32("UserId"));
                    Debug.WriteLine("user => " + (user != null));
                    if (user != null)
                    {
                        user.Id_Estabelecimento = estabelecimento.Id;
                        _context.Update(user);
                        _context.SaveChanges();
                        _context.Database.CommitTransaction();
                        Debug.WriteLine("funcionou?");
                        return RedirectToAction("Index", "UsuarioEstabelecimento");
                    }
                    else
                    {
                        return View(new ErrorViewModel { RequestId = "Usuário não encontrado" });
                    }
                }
                else  //Update
                {
                    Debug.WriteLine("Editar Estabelecimento");
                    _context.Estabelecimento.Update(estabelecimento);
                    _context.SaveChanges();
                    _context.Database.CommitTransaction();
                    Debug.WriteLine("Estabelecimento Atualizado");
                }
                return RedirectToAction("Index", "UsuarioEstabelecimento");
            }
            catch (Exception ex)
            {
                // Em caso de erro, desfaz todas as alterações no banco de dados
                _context.Database.RollbackTransaction();

                Debug.WriteLine("Erro durante a operação: " + ex.Message);
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, ex,
                    naoProcureEstabelecimento: true);
                return View(new ErrorViewModel { RequestId = ex.Message });
            }
            
        }
        public async Task<IActionResult> EditarEstabelecimento()  //Chama a tela de editar
        {
            UsuarioEstabelecimentoModel user = null;
            try
            {
                Debug.WriteLine("Chamou a tela de Editar Estabelecimento!");
                user = _context.UsuariosEstabelecimento.FirstOrDefault(o => o.Id == HttpContext.Session.GetInt32("UserId"));
                if (user != null)
                {
                    var estab = _context.Estabelecimento.FirstOrDefault(o => o.Id == user.Id_Estabelecimento);
                    if (estab != null && user.Id_Estabelecimento!=null)
                    {
                        EstabelecimentoViewModel estabelecimento = new EstabelecimentoViewModel();
                        estabelecimento.Id = (int)user.Id_Estabelecimento;
                        estabelecimento.Nome = estab.Nome;

                        return View("CadastroEstabelecimento", estabelecimento);
                    }
                    else
                    {
                        return View(new ErrorViewModel { RequestId = "Estabelecimento não encontrado" });
                    }
                }
                else
                {
                    Debug.WriteLine("Usuário não encontrado");
                    Debug.WriteLine("user -> " + user);
                    return View(new ErrorViewModel { RequestId = "Usuário não encontrado" });
                }
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err,
                    EstabelecimentoID: user!=null ?user.Id_Estabelecimento:null);

                return View(new ErrorViewModel { RequestId = "Usuário não encontrado" });
            }
        
        }
    }
}

GuideMeServerMVC/Controllers/UsuarioEstabelecimentoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GuideMeServerMVC.Models;
using Microsoft.AspNetCore.Authorization;
using GuideMeServerMVC.Data;
using GuideMeServerMVC.TO;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Filters;
using GuideMeServerMVC.Utils;
using System.Reflection;

namespace GuideMeServerMVC.Controllers
{
 
    public class UsuarioEstabelecimentoController : ControllerAutenticado<UsuarioEstabelecimentoModel>
    {
        private readonly GuidemeDbContext _context;

        public UsuarioEstabelecimentoController(GuidemeDbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index()
        {

            try
            {
                Debug.WriteLine("Chamou a tela de Index!");
                var user = _context.UsuariosEstabelecimento.FirstOrDefault(o => o.Id == HttpContext.Session.GetInt32("UserId"));
                EstabelecimentoViewModel estabelecimento = new EstabelecimentoViewModel();
                try
                {
                    estabelecimento = _context.Estabelecimento.FirstOrDefault(o => o.Id == user.Id_Estabelecimento);
                }
                catch (Exception ex) { estabelecimento = null; }

                MenuViewModel menuModel = new MenuViewModel();
                menuModel.UsuarioEstabelecimento = user;
                menuModel.Estabelecimento = estabelecimento;

                return View("Menu", menuModel);
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        

        public async Task<IActionResult> CreateUsuario(UsuarioEstabelecimentoModel usuario)
        {
            try
            {
                _context.UsuariosEstabelecimento.Add(usuario);
                _context.SaveChanges();
                return Ok("Teste Post");
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }

           
        }

       
    }
}

GuideMeServerMVC/Views/UsuarioEstabelecimento/Cadastro.cshtml
@using GuideMeServerMVC.Models
@model UsuarioEstabelecimentoModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div>
        <h2>Cadastro de Usuário</h2>
        <form asp-action="CreateUsuario" method="post" enctype="multipart/form-data">
            <label for="login" class="control-label">Login</label>
            <input type="text" Name="Login" value="@Model.Login" class="form-control" />
            <span asp-validation-for="Login" class="text-danger"></span>
            <br />

            <label for="senha" class="control-label">Senha</label>
            <input type="password" Name="Senha" value="@Model.Senha" class="form-control" />
            <span asp-validation-for="Senha" class="text-danger"></span>
            <br />

            <label for="admin" class="control-label">Admin?</label>
            <input type="checkbox" name="Admin" value="true" checked />
            <span asp-validation-for="Admin" class="text-danger"></span>
            <br />

            <input type="submit" value="Criar novo usuário" class="btn-info" />
            &nbsp;&nbsp;&nbsp;
            <a href="/Home/index" class="btn-light">Voltar</a>
            <br />
        </form>
    </div>
</body>

GuideMeServerMVC/Views/UsuarioEstabelecimento/Menu.cshtml
@using GuideMeServerMVC.Models
@model MenuViewModel
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container px-4 py-5">
        <!-- <h2>Menu</h2> -->
        @if (Model.UsuarioEstabelecimento != null && Model.UsuarioEstabelecimento.Id_Estabelecimento >= 0)
        {
            <h2><b>Estabelecimento Atual: @Model.Estabelecimento.Nome</b></h2>
        }
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            @if (Model.UsuarioEstabelecimento != null && Model.UsuarioEstabelecimento.Id_Estabelecimento >= 0)
            {
                <div class="feature col card" style="text-align:center; margin:8px; background-color:#caf0f8">
                    <div class="feature-icon d-inline-flex align-items-center justify-content-center fs-2 mb-3" style="margin:8px">
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-bank" viewBox="0 0 16 16">
                            <path d="m8 0 6.61 3h.89a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v7a.5.5 0 0 1 .485.38l.5 2a.498.498 0 0 1-.485.62H.5a.498.498 0 0 1-.485-.62l.5-2A.501.501 0 0 1 1 13V6H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 3h.89L8 0ZM3.777 3h8.447L8 1 3.777 3ZM2 6v7h1V6H2Zm2 0v7h2.5V6H4Zm3.5 0v7h1V6h-1Zm2 0v7H12V6H9.5ZM13 6v7h1V6h-1Zm2-1V4H1v1h14Zm-.39 9H1.39l-.25 1h13.72l-.25-1Z" />
                        </svg>
                    </div>
                    <div style="display:flex; flex-direction:column">
                        <h3 class="fs-2 text-body-emphasis">Estabelecimentos</h3>
                        <a asp-controller="Estabelecimento" asp-action="EditarEstabelecimento" class="btn-light">Editar Estabelecimento</a>
                    </div>
                </div>

                <a asp-controller="Tag" asp-action="ExibirTagsEstabelecimento" class="feature col card" style="text-align:center; margin:8px; background-color:#caf0f8">
                    <div class="feature-icon d-inline-flex align-items-center justify-content-center fs-2 mb-3" style="margin:8px">
                        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-tag" viewBox="0 0 16 16">
                            <path d="M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z" />
                            <path d="M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z" />
                        </svg>
                    </div>
                        <h3 class="fs-2 text-body-emphasis">Tags</h3>                       
                </a>
            }
            else
            {
                <a asp-controller="Estabelecimento" asp-action="CadastrarEstabelecimento" class="btn-light">Cadastrar Estabelecimento</a>
            }
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>