GuideMeServerMVC/Models/TagViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GuideMeServerMVC.Models
{
    [Table("tbTags")]
    public class TagViewModel:BaseViewModel
    {
        
        [Column("TAG")]
        public string TagId { get; set; }
        [Column("ID_ESTABELECIMENTO")]
        public int EstabelecimentoId { get; set; }
        [Column("ID_TIPO_TAG")]
        public int tipoTag { get; set; }
        [Column("NOME")]
        public string Nome { get; set; }

        [NotMapped]
        public List<TagsPaiViewModel>? TagsPai { get; set; }
    }
}

GuideMeServerMVC/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using GuideMeServerMVC.Models;
using Microsoft.AspNetCore.Authorization;
using GuideMeServerMVC.Data;
using GuideMeServerMVC.TO;
using System.Security.Claims;
using System.Diagnostics;
using Newtonsoft.Json;
using GuideMeServerMVC.Enum;
using Microsoft.EntityFrameworkCore;
using System.Runtime.Intrinsics.Arm;
using Azure;
using GuideMeServerMVC.Utils;
using System;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Reflection;
using GuideMeServerMVC.Services;
//using GuideMeServerMVC.Utils;

namespace GuideMeServerMVC.Controllers
{
    public class TagController : ControllerAutenticado<LugaresViewModel>
    {
        private readonly GuidemeDbContext _context;
        private readonly TagService _service;
        private readonly TagsPaiService _serviceTagsPai;
        public TagController(GuidemeDbContext context)
        {
            _context = context;
            _service = new TagService(_context);
            _serviceTagsPai = new TagsPaiService(_context);
        }
        public async Task<IActionResult> Index()
        {

            try
            {
                return View("TagsEstabelecimento", await _service.GetTagsUsuario((int)_UsuarioLogado));
            }
             catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }

      


        protected virtual void ValidaDados(CadastrarAssociacaoTagsTO model,out TagViewModel _menorTag,out TagViewModel _maiorTag)
        {
            ModelState.Clear();
            _menorTag = null;
            _maiorTag = null;
            var erros =_service.ValidarDadosAssociacaoTags(model,out _menorTag,out _maiorTag);
            if (erros != null && erros.Count > 0)
            {
                foreach (KeyValuePair<string, string> erro in erros)
                    ModelState.AddModelError(erro.Key, erro.Value);

            }

        }

        public async Task<IActionResult> SaveAssociacaoTags(CadastrarAssociacaoTagsTO model)
        {
            try
            {

                VerificaUserLogado();
 
                TagViewModel menorTag = null, maiorTag=null;

                ValidaDados(model, out menorTag, out maiorTag);

                if (ModelState.IsValid == false)
                    return View("AssociarTags", await _service.GetDadosCadastroAssociacao(HelperControllers.GetUserLogadoID(HttpContext.Session)));
                else
                {
                    await _service.SalvarAssociacao(model, menorTag, maiorTag);

                    return View("TagsEstabelecimento", await _service.GetTagsUsuario((int)_UsuarioLogado));
                }
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }

        public async Task<IActionResult> VisualizarRelacionamentos(int Id)
        {
            try
            {
                ContainerAssociacaoTagsTO container = await _service.GetAssociacoesTag(Id);

                if(container != null)
                    return View("RelacionamentoTags", container);

                return View("TagsEstabelecimento", await _service.GetTagsUsuario((int)_UsuarioLogado));
                
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }


        public virtual async Task<IActionResult> TelaEditar(int Id)
        {

            try
            {
                Debug.WriteLine("TelaEditar");
                var tag = _context.Tags.FirstOrDefault(o => o.Id == Id);
                if (tag != null)
                {
                    return View("EditarTag", tag);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
            
        }

        public async Task<IActionResult> ExibirTagsEstabelecimento()
        {

            try
            {
                Debug.WriteLine("Listando Tags");
                return View("TagsEstabelecimento", await _service.GetTagsUsuario((int)_UsuarioLogado));
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }

        }

        public virtual async Task<IActionResult> UpdateTag([FromForm] TagViewModel model)
        {

            try
            {
                await _service.UpdateAsync(model);
                return View("TagsEstabelecimento", await _service.GetTagsUsuario((int)_UsuarioLogado));
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }

           
        }


        public async Task<IActionResult> Delete(int id)
        {

            try
            {
               await _service.Delete(id,(int)_UsuarioLogado);

                return RedirectToAction("ExibirTagsEstabelecimento", "Tag");
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }


           
        }
        public async Task<IActionResult> DeleteRelacionamento(int idTagPrincipal, int idTagSecundaria)
        {

            try
            {
               await _serviceTagsPai.DeletarRelacionamentos(idTagPrincipal, idTagSecundaria);
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }

            return RedirectToAction("ExibirTagsEstabelecimento", "Tag");

        }
        public async Task<IActionResult> AssociarTags()
        {
            try
            {
                return View("AssociarTags", await  _service.GetDadosCadastroAssociacao(HelperControllers.GetUserLogadoID(HttpContext.Session)));
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }

     
    }
   

}

GuideMeServerMVC/Controllers/UsuarioEstabelecimentoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GuideMeServerMVC.Models;
using Microsoft.AspNetCore.Authorization;
using GuideMeServerMVC.Data;
using GuideMeServerMVC.TO;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Filters;
using GuideMeServerMVC.Utils;
using System.Reflection;

namespace GuideMeServerMVC.Controllers
{
 
    public class UsuarioEstabelecimentoController : ControllerAutenticado<UsuarioEstabelecimentoModel>
    {
        private readonly GuidemeDbContext _context;

        public UsuarioEstabelecimentoController(GuidemeDbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index()
        {

            try
            {
                Debug.WriteLine("Chamou a tela de Index!");
                var user = _context.UsuariosEstabelecimento.FirstOrDefault(o => o.Id == HttpContext.Session.GetInt32("UserId"));
                EstabelecimentoViewModel estabelecimento = new EstabelecimentoViewModel();
                try
                {
                    estabelecimento = _context.Estabelecimento.FirstOrDefault(o => o.Id == user.Id_Estabelecimento);
                }
                catch (Exception ex) { estabelecimento = null; }

                MenuViewModel menuModel = new MenuViewModel();
                menuModel.UsuarioEstabelecimento = user;
                menuModel.Estabelecimento = estabelecimento;

                return View("Menu", menuModel);
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        

        public async Task<IActionResult> CreateUsuario(UsuarioEstabelecimentoModel usuario)
        {
            try
            {
                _context.UsuariosEstabelecimento.Add(usuario);
                _context.SaveChanges();
                return Ok("Teste Post");
            }
            catch (Exception err)
            {
                _ = HelperControllers.LoggerErro(HttpContext.Session, _context, this.GetType().Name, MethodBase.GetCurrentMethod().Name, err);
                return View("Error", new ErrorViewModel(err.ToString()));
            }

           
        }

       
    }
}

GuideMeServerMVC/Views/Tag/AssociarTags.cshtml
@using  GuideMeServerMVC.TO
@model CadastrarAssociacaoTagsTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2 style="text-align: center">Associação de Tags</h2>
        </div>
        <div class="card-body" style="margin-top:16px">
            <form asp-action="SaveAssociacaoTags" method="post">
                <input type="hidden" name="Operacao" value="@ViewBag.Operacao" />
                <input type="hidden" name="Itens" value="@Model.TagsDiponiveis" />

                <label for="TagPrincipalSelecionada" class="control-label">Tag principal</label>
                <select asp-for="TagPrincipalSelecionada" asp-items="@Model.TagsDiponiveis" class="form-control"> </select>
                <span asp-validation-for="TagPrincipalSelecionada" class="text-danger"></span>
                <br />

                <label for="TagPrincipalSecundaria" class="control-label">Tag Secundaria</label>
                <select asp-for="TagSecundariaSelecionada" asp-items="@Model.TagsDiponiveis" class="form-control"> </select>
                <span asp-validation-for="TagSecundariaSelecionada" class="text-danger"></span>
                <br />

                <label for="DirecaoSelecionada" class="control-label">Tag Secundaria</label>
                <select asp-for="DirecaoSelecionada" asp-items="@Model.DirecoesDisponiveis" class="form-control"> </select>
                <span asp-validation-for="DirecaoSelecionada" class="text-danger"></span>
                <br />

                <div class="form-group text-center">
                    <input type="submit" value="Associar Tags" class="btn btn-primary rounded-pill px-3" />
                    &nbsp;&nbsp;&nbsp;
                    <a href="#" onclick='javascript:history.back(-1);' class="btn btn-secondary rounded-pill px-3">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>

GuideMeServerMVC/Views/Tag/EditarTag.cshtml
@using GuideMeServerMVC.Models
@model TagViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; //enctype="multipart/form-data"
}
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2 style="text-align: center">Edição de Tag</h2>
            </div>

            <div class="card-body" style="margin-top:16px">
                <form asp-action="UpdateTag" method="post">
                    <div class="row g-3">
                        <div class="col-sm-12">
                            <input type="text" Name="TagId" value="@Model.TagId" class="form-control" style="display: none;" />
                            <span asp-validation-for="TagId" class="text-danger"></span>
                        </div>
                        <div class="col-sm-12">
                            <input type="text" Name="EstabelecimentoId" value="@Model.EstabelecimentoId" class="form-control" style="display: none;" />
                            <span asp-validation-for="EstabelecimentoId" class="text-danger"></span>
                        </div>
                        <div class="col-sm-12">
                            <input type="text" Name="tipoTag" value="@Model.tipoTag" class="form-control" style="display: none;" />
                        </div>
                        <div class="col-sm-12">
                            <label for="Nome" class="form-label">Nome</label>
                            <input type="text" Name="Nome" value="@Model.Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>

                    <input hidden type="text" Name="Id" value="@Model.Id" class="form-control" />
                    <br />

                    <div class="form-group text-center">
                        <input type="submit" value="Salvar" class="btn btn-primary rounded-pill" />
                        &nbsp;&nbsp;&nbsp;
                        <a asp-controller="Tag" asp-action="ExibirTagsEstabelecimento" class="btn btn-secondary rounded-pill px-3">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

GuideMeServerMVC/Views/Tag/RelacionamentoTags.cshtml
@using GuideMeServerMVC.TO
@model ContainerAssociacaoTagsTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="text-align: center">Relacionamentos da Tag @Model.TagOriginal.Nome</h2>


<div style="text-align: center; margin-top:16px">
    <a class="btn btn-primary rounded-pill px-3" href="/Tag/AssociarTags">Associar Tags</a>
</div>

<table class="table-responsive table-striped" style="text-align: center; width:100%; margin-top:16px">
    <thead>
        <tr>
            <th>Tag Principal</th>
            <th>Tag Secundaria</th>
            <th>Direção</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (AssociacaoTagTO a in Model.Relacionamentos)
        {
            <tr>

                <td>@a.TagPrincipal.Nome</td>
                <td>@a.TagSecundaria.Nome</td>
                <td>@a.Direcao</td>
                <td>
                    <a href="javascript:apagarRegistroRelacionamentoTag(@a.TagPrincipal.Id,@a.TagSecundaria.Id, 'Tag')" class="btn btn-danger">Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="#" onclick='javascript:history.back(-1);' class="btn btn-secondary rounded-pill px-3" style="margin-top:16px">Voltar</a>

<style>
    tbody tr:nth-child(odd) {
        background-color: #ade8f4;
    }

    tbody tr:nth-child(even) {
        background-color: #caf0f8;
    }

    tbody tr {
        background-image: url(noise.png);
    }

    table {
        background-color: #00b4d8;
        border-collapse: collapse;
        border: 1px solid #0C2D48;
    }

    th, td {
        border: 1px solid #03045e;
        padding: 5px;
    }
</style>

GuideMeServerMVC/Views/Tag/TagsEstabelecimento.cshtml
@model List<TagViewModel> //
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Lista de Tags do Estabelecimento</title>
</head>
<body>
    <h2 style="text-align: center">Lista de Tags do Estabelecimento</h2>

    <div style="text-align: center; margin-top:16px">
        <a class="btn btn-primary rounded-pill px-3" href="/Tag/AssociarTags">Associar Tags</a>
    </div>
    
    <table id="tblTags" class="table-responsive table-striped" style="text-align: center; width:100%; margin-top:16px">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tag ID</th>
                <th>Nome</th>
                <th>Tipo de Tag</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var tag in Model)
            {
                <tr>
                    <td class="Id">
                        <span>@tag.Id</span>
                    </td>
                    <td class="TagId">
                        <span>@tag.TagId</span>
                        <input type="text" value="@tag.TagId" style="display:none" />
                    </td>
                    <td class="Nome">
                        <span>@tag.Nome</span>
                        <input type="text" value="@tag.Nome" style="display:none" />
                    </td>
                    <td class="tipoTag">
                        <span>@tag.tipoTag</span>
                        <input type="number" value="@tag.tipoTag" style="display:none" />
                    </td>
                    <td>
                        <a class="btn btn-info" style="background-color:#0096c7; color:#FFF" asp-controller="Tag" asp-action="TelaEditar" asp-route-id="@tag.Id">Editar</a> 
                        <a href="javascript:apagarRegistro(@tag.Id, 'Tag')" class="btn btn-danger">Apagar</a> 
                        <a class="btn btn-info" style="background-color:#0077b6; color:#FFF" asp-controller="Tag" asp-action="VisualizarRelacionamentos" asp-route-id="@tag.Id">Visualizar tags relacionadas</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    <!-- Adicione aqui elementos HTML adicionais, como botões ou links -->
    <a asp-controller="UsuarioEstabelecimento" asp-action="Index" class="btn btn-secondary rounded-pill px-3" style="margin-top:16px" >Voltar</a>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">
        //Delete event handler.
        $("body").on("click", "#tblTags .Delete", function () {
            console.log("Delete event fired!");
                if (confirm("Do you want to delete this row?")) {
                    var row = $(this).closest("tr");
                    var Id = row.find("span").html();
                    console.log("Id: " + Id);
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("DeleteTag", "Tag")',
                        data: JSON.stringify({ Id: Id }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (response) {
                            if ($("#tblTags tr").length > 2) {
                                row.remove();
                            } else {
                                //row.find(".Edit").hide();
                                row.find(".Delete").hide();
                                row.find("span").html('&nbsp;');
                            }
                        }
                    });
                }
            });
        //Edit event handler.
        $("body").on("click", "#tblTags .Edit", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    $(this).find("input").show();
                    $(this).find("span").hide();
                }
            });
            row.find(".Update").show();
            row.find(".Cancel").show();
            row.find(".Delete").hide();
            $(this).hide();
        });
        //Update event handler.
        $("body").on("click", "#tblTags .Update", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    span.html(input.val());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Cancel").hide();
            $(this).hide();

            var tag = {};
            tag.Id = row.find(".Id").find("span").html();
            tag.TagId = row.find(".TagId").find("span").html();
            tag.Nome = row.find(".Nome").find("span").html();
            tag.tipoTag = row.find(".tipoTag").find("span").html();
            $.ajax({
                type: "POST",
                url: '@Url.Action("DeleteTag", "Tag")',
                data: JSON.stringify({ Id: tag.Id, TagId: tag.TagId, Nome: tag.Nome, tipoTag: tag.tipoTag }),
                //data: '{tag:' + JSON.stringify(tag) + '}',
                contentType: "application/json; charset=utf-8",
                dataType: "json"
            });
        });
        //Cancel event handler.
        $("body").on("click", "#tblTags .Cancel", function () {
            var row = $(this).closest("tr");
            $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    var span = $(this).find("span");
                    var input = $(this).find("input");
                    input.val(span.html());
                    span.show();
                    input.hide();
                }
            });
            row.find(".Edit").show();
            row.find(".Delete").show();
            row.find(".Update").hide();
            $(this).hide();
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
<style>
    tbody tr:nth-child(odd) {
        background-color: #ade8f4;
    }

    tbody tr:nth-child(even) {
        background-color: #caf0f8;
    }

    tbody tr {
        background-image: url(noise.png);
    }

    table {
        background-color: #00b4d8;
        border-collapse: collapse;
        border: 1px solid #0C2D48;
    }

    th, td {
        border: 1px solid #03045e;
        padding: 5px;
    }
</style>